development:
  host: 'localhost'
  port: 8529
  database: 'geograph'
  username: 'root'
  password: 'your_password'  # Remember to change this
  graph_name: 'supply_chain'

collections:
  vertices:
    - name: 'products'
      key_field: 'product_id'
    - name: 'parts'
      key_field: 'part_id'
    - name: 'suppliers'
      key_field: 'supplier_id'
    - name: 'warehouses'
      key_field: 'warehouse_id'
    - name: 'purchase_orders'
      key_field: 'po_id'
    - name: 'risk_factors'
      key_field: 'risk_id'
    - name: 'inventory'
      key_field: 'inventory_id'
    - name: 'inventory_transactions'
      key_field: 'transaction_id'

  edges:
    - name: 'supplier_provides_part'
      from_collection: 'suppliers'
      to_collection: 'parts'
    - name: 'part_depends_on'
      from_collection: 'parts'
      to_collection: 'parts'
    - name: 'order_to_part'
      from_collection: 'purchase_orders'
      to_collection: 'parts'
    - name: 'order_to_supplier'
      from_collection: 'purchase_orders'
      to_collection: 'suppliers'
    - name: 'part_inventory_level'
      from_collection: 'parts'
      to_collection: 'inventory'
    - name: 'supplier_has_risk'
      from_collection: 'suppliers'
      to_collection: 'risk_factors'
    - name: 'inventory_transaction'
      from_collection: 'inventory'
      to_collection: 'inventory_transactions'